### ISSUE TITLE
What to do if a database has only mapped drugs to ingredient level?

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/FluroquinolonesStudyathon#19]
We have at least one data partner (@jennifercelane) that has drugs mapped to ingredient level. But we restriced to specific dose forms  https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/blob/8b6726f5ab198d02c323821fc176a25140ee74aa/1_StudyCode/RunAnalysis.R#L47, which drops all their records. Should we include these ingredient level records? (Or have a set of cohort definitions that include all concepts for the ingredient)?

**Comment by daniprietoalhambra** [comment]
I would include ingredient-level records, but only for incidence/prevalence

**Comment by vvcb** [comment]
Lancs also have drugs mapped to ingredient level although we do have route (oral, iv, eye, tube(?!)) in `route_source_value`. @quindavies just removed the doseForm parameter.

**Comment by ajoedicke** [comment]
I'd be happy to include ingredient records. We can do indication, too, and just skip the drug utilization analyses for dose and duration.
