### ISSUE TITLE
Error calling `DrugExposureDiagnostics::executeChecks` - `table dbplyr_00n already exists and overwrite is FALSE!`

### ISSUE THREAD

**Issue by vvcb** [oxford-pharmacoepi/FluroquinolonesStudyathon#22]
A section of code in [`RunAnalysis.R`, (Lines 77-L88)](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/blob/main/1_StudyCode/RunAnalysis.R#L77-L88) causes the same error when executing against Microsoft SQL Server despite numerous attempts all day. This is about a temporary table already existing - see below.

I have had no luck running this code despite trying all day. I have tried the following:

- Restart R session
- Clear environment
- Only one of us (@quindavies) executing this against our OMOP instance with some success but not entirely - the session fails right at the end in this case. 
- Add `tablePrefix = 'vc_` as a parameter in the `executeChecks` function call. Documentation suggests this should create permanent rather than temporary tables. 7 tables do appear in the write schema before the same error appears.

```R
drug_diagnostics <-   DrugExposureDiagnostics::executeChecks(
  cdm = cdm,
  ingredients = drug_ingredients$concept_id,
  subsetToConceptId = unique(purrr::list_c(drug_concepts)),
  checks = c(
    "missing",
    "exposureDuration",
    "sourceConcept"
  ),
  verbose=TRUE)
```

```bash
Progress: getting descendant concepts of ingredient (1797513) used in database
Progress: getting descendant concepts of ingredient
Progress: adding drug strength info
Progress: limiting to concepts in the db
Progress: adding concept names
Created a temporary table named #dbplyr_013
Overall time taken: 0 minutes and 5 seconds
Time taken: 0 minutes and 5 seconds
Progress: getting drug strength for ingredient
Time taken: 0 minutes and 3 seconds
Progress: getting drug records for ingredient
Time taken: 0 minutes and 4 seconds
Progress: get concepts used
Time taken: 0 minutes and 3 seconds
Progress: sampling drug records
Error in `CDMConnector::computeQuery()`:
! table dbplyr_014 already exists and overwrite is FALSE!
Run `rlang::last_trace()` to see where the error occurred.
Warning messages:
1: Your SQL query is over 10,000 characters which can cause issues on some database platforms!
Try calling computeQuery earlier in your pipeline. 
2: Your SQL query is over 10,000 characters which can cause issues on some database platforms!
Try calling computeQuery earlier in your pipeline. 
```

**Comment by edward-burn** [comment]
Workaround implemented using random number to start temp tables (to avoid conflicts between users)
