### ISSUE TITLE
ITS- Control series

### ISSUE THREAD

**Issue by Braventos** [oxford-pharmacoepi/FluroquinolonesStudyathon#25]
Please, consider adding a control series not impacted by the intervention (perhaps another antibiotic?) to improve the validity of the results. 
[](https://academic.oup.com/ije/article/47/6/2082/5049576?login=true)

**Comment by edward-burn** [comment]
@ajoedicke @daniprietoalhambra to discuss if we could add this (might also be interesting for comparing characteristics pre and post, etc)

We could add both 1) other antibiotics as a positive control and 2) one or more negative controls

**Comment by daniprietoalhambra** [comment]
I'm very late to this, but I think we can live without this
