### ISSUE TITLE
Add specific comorbidities to summarise

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/FluroquinolonesStudyathon#3]
```
9.3.3.2	Covariates to be assessed for Objective 2
[....]
•	Comorbidities of interest (recorded any time, and in the 365- and 30-day period before index date):
o	Chronic kidney disease
o	Solid organ transplant
```

**Comment by ajoedicke** [comment]
Co-morbidities for FQs - from MHRA

Risk factors for tendinopathies
•	Age ≥60 years
•	Tobacco use
•	Concomitant use of corticosteroids
•	Renal impairment
•	Solid organ transplant

Risk factors for aortic aneurysm/dissection
•	Age ≥60 years
•	Tobacco use
•	Concomitant use of corticosteroids
•	Cardiac or renal transplant
•	Vascular aneurysms
•	Aortic valve disorder
•	Hypertension
•	Lipid disorder
•	Ischaemic heart disease 
•	Cerebrovascular disease
•	Connective tissue disorders (Marfan’s syndrome, Ehlers-Danlos syndrome, Loeys-Dietz syndrome, Turner's Syndrome)
•	Traumatic motor vehicle accident
•	Chronic obstructive pulmonary disease
•	Congenital heart valve disease
•	Family history of aneurysm disease
•	Behcet's disease
•	Rheumatoid arthritis
•	Takayasu arteritis or giant cell arteritis
•	Atherosclerosis
•	Sjögren's syndrome
•	Infective endocarditis

Risk factors for lowered seizure threshold/seizures
•	Epilepsy
•	Seizures

Risk factors for QT prolongation
•	Age ≥60 years
•	Vascular aneurysms
•	Hypertension

Risk factors for haemolytic reactions
•	Glucose-6-phosphate dehydrogenase deficiency

Risk factors for exacerbation of myasthenia gravis
•	Myasthenia gravis

**Comment by ajoedicke** [comment]
[copd.json](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/files/13499138/copd.json)
[rheumatoid_arthritis.json](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/files/13499139/rheumatoid_arthritis.json)
[hypertension.json](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/files/13499140/hypertension.json)
[[lc_highrisk] sidiap_solid_organ_transplant_receipient_v2 (1).json](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/files/13499142/lc_highrisk.sidiap_solid_organ_transplant_receipient_v2.1.json)

**Comment by ajoedicke** [comment]
[chronicKidneyDisease01 (3).json](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/files/13499195/chronicKidneyDisease01.3.json)
[myastheniaGravis01.json](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/files/13499197/myastheniaGravis01.json)

**Comment by ajoedicke** [comment]
@edward-burn 

Jsons for concept sets comorbidities and comedication for Table 1 patient charaterisation are here:

https://unioxfordnexus-my.sharepoint.com/personal/orms0426_ox_ac_uk/_layouts/15/onedrive.aspx?FolderCTID=0x01200079640BB368F60B4EB884F8ABD3DC3202&id=%2Fpersonal%2Forms0426%5Fox%5Fac%5Fuk%2FDocuments%2Fmhra%20studyathon%2Ffluroquinolones%2Fcomorbidities%5FJSON

Can we please have time windows as specified in the folders:
(1) conditions recorded anytime before index date
(2) comedication 1 yr before index date
(3) comedication within 30days before index dates (thats for all antibiotics)
(4) tests (results from AB cultures/antibiograms) within 14days before and 7 days after index date

**Comment by edward-burn** [comment]
Added (@ajoedicke please open a new issue if we want to revise the list etc)
