### ISSUE TITLE
Issues Installing the V8 and RPostgres packages on Ubuntu 

### ISSUE THREAD

**Issue by solmazeradat** [oxford-pharmacoepi/FluroquinolonesStudyathon#9]
Hi,

I am running the code on behalf of Great Ormond Street Hospital. 

When running the **CodeToRun.R** script on a Ubuntu machine, came across the following error message when installing the Package V8: 

![image](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/assets/11243960/bee97a9b-5c05-4682-af29-1adfbe42effd)

I ran the following command in the terminal window 

![image](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/assets/11243960/ce8b5f27-50e1-4cc9-8eb3-d67a9c80b3ef)

Reran the code from the top and it seems the issue resolved. 

Similarly, for RPostgres, got the following error: 

![image](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/assets/11243960/86619dff-fbfa-47f5-a53b-19c49a91c96e)

Running the command below on a terminal window and rerunning the code fixed the issue: 

![image](https://github.com/oxford-pharmacoepi/FluroquinolonesStudyathon/assets/11243960/72d55948-5de5-45d7-9dcb-9bfaae58c4c3)

Thought it be good to share this with the project. 

Many thanks,
Solmaz

**Comment by edward-burn** [comment]
Thanks for reporting @solmazeradat and installing all those
